services:
  db:
    image: mysql
    container_name: mysql_backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3306:3306"
    volumes:
      - group6:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  group6:
